In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from feature_engine.datetime import DatetimeFeatures
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [4]:
import joblib

In [5]:
train_df=pd.read_csv("data/train.csv")

In [6]:
train_df.head()

,airline,date_of_journey,source,destination,dep_time,arrival_time,duration,total_stops,additional_info,price
0,Jet Airways,2019-06-21,Mumbai,Hyderabad,10:20:00,11:50:00,90,0.0,In-flight meal not included,4995
1,Air India,2019-05-18,Delhi,Cochin,09:00:00,07:40:00,1360,1.0,No Info,8372
2,Air India,2019-06-12,Kolkata,Banglore,09:10:00,11:05:00,1555,2.0,No Info,6117
3,Vistara,2019-04-01,Kolkata,Banglore,20:20:00,22:55:00,1595,1.0,No Info,7770
4,Vistara,2019-06-06,Kolkata,Banglore,17:00:00,10:45:00,1065,1.0,No Info,9187

In [7]:
def split_data(data):
    x=data.drop(columns=["price"])
    y=data["price"]
    return x,y

In [8]:
x_train,y_train=split_data(train_df)

In [9]:
x_val,y_val=split_data(pd.read_csv("data/val.csv"))

In [10]:
x_test,y_test=split_data(pd.read_csv("data/test.csv"))

In [11]:
x_train.head()

,airline,date_of_journey,source,destination,dep_time,arrival_time,duration,total_stops,additional_info
0,Jet Airways,2019-06-21,Mumbai,Hyderabad,10:20:00,11:50:00,90,0.0,In-flight meal not included
1,Air India,2019-05-18,Delhi,Cochin,09:00:00,07:40:00,1360,1.0,No Info
2,Air India,2019-06-12,Kolkata,Banglore,09:10:00,11:05:00,1555,2.0,No Info
3,Vistara,2019-04-01,Kolkata,Banglore,20:20:00,22:55:00,1595,1.0,No Info
4,Vistara,2019-06-06,Kolkata,Banglore,17:00:00,10:45:00,1065,1.0,No Info

In [12]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   airline          640 non-null    object
 1   date_of_journey  640 non-null    object
 2   source           640 non-null    object
 3   destination      640 non-null    object
 4   dep_time         640 non-null    object
 5   arrival_time     640 non-null    object
 6   duration         640 non-null    int64
 7   total_stops      640 non-null    float64
 8   additional_info  640 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 45.1+ KB

In [1]:
dt_cols=["date_of_journey","dep_time","arrival_time"]
num_cols=["duration","total_stops",]
str_cols=["airline","source","destination","additional_info"]

In [8]:
num_transformer=Pipeline(steps=[("imputer",SimpleImputer(strategy="median")),("scaler",StandardScaler())])
str_transformer=Pipeline(steps=[("encoder",OneHotEncoder(sparse_output=False)),("imputer",SimpleImputer(strategy="most_frequent"))])
doj_transformers=Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),("extractor",DatetimeFeatures(features_to_extract=["day_of_week","day_of_month","month","week"],format="mixed")),("scaler",StandardScaler())])
time_transformers=Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),("extractor",DatetimeFeatures(features_to_extract=["hour","minute"],format="mixed")),("scaler",StandardScaler())])

In [ ]:
preprocessor=ColumnTransformer(transformers=[("num",num_transformer,num_cols),("str",str_transformer,str_cols)])